name: rss
description: rss feed list
publish_to: none

version: 1.0.0+2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  webfeed: ^0.7.0
  flutter_bloc: ^8.0.0
  freezed_annotation: ^1.0.0
  json_annotation: ^4.3.0
  riverpod: ^1.0.0
  fpdart: ^0.0.12
  cached_network_image: ^3.1.0+1
  intl: ^0.17.0
  audioplayers: ^0.20.1
  provider: ^6.0.1
  just_audio: ^0.9.18
  flutter_html: ^2.1.5
  time: ^2.0.1
  flutter_widgetkit: ^1.0.3
  home_widget: ^0.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  freezed: ^1.0.0
  json_serializable: ^6.0.1
  build_runner: ^2.1.5
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  image_path: "assets/icon/rss_feed_icon.png"
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/files/guardian.xml

scripts: derry.yaml 
